<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Jyotis Joy" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<p>##Introduction:</p>
<pre class="r"><code>work_dir &lt;-&quot;/stor/home/jj37257/website/content/project&quot;
affair &lt;- read.csv(&quot;Affairs.csv&quot;)
affair$X &lt;- NULL</code></pre>
<p>This is the ‘affairs’ dataset, which is a dataset containing information on infidelity, known as Fair’s Affairs. The data was attained using cross-section from a survey conducted by Psychology Today in 1969. It contains the following variables: number of affairs, the person’s gender and age,the number of years they were married, number of children they have,their religiousness, education level, occupation, and their rating of marriage. There are 601 observations and 9 variables in the data set.</p>
<p>##MANOVA Testing:</p>
<pre class="r"><code>library(rstatix)
t &lt;- affair$gender
u &lt;- affair%&gt;% select(affairs, yearsmarried,age,rating)
sapply(split(u, t), mshapiro_test)</code></pre>
<pre><code>##           female       male        
## statistic 0.9329811    0.9486016   
## p.value   1.025729e-10 1.835357e-08</code></pre>
<pre class="r"><code>lapply(split(u,t), cov) </code></pre>
<pre><code>## $female
##                affairs yearsmarried       age    rating
## affairs      10.951228     3.530636  3.115256 -1.063816
## yearsmarried  3.530636    31.665797 39.921732 -2.003607
## age           3.115256    39.921732 74.757482 -2.521560
## rating       -1.063816    -2.003607 -2.521560  1.318006
## 
## $male
##                affairs yearsmarried       age    rating
## affairs      10.840339     3.325507  2.566998 -0.968691
## yearsmarried  3.325507    30.398290 40.099491 -0.935346
## age           2.566998    40.099491 92.678337 -1.483941
## rating       -0.968691    -0.935346 -1.483941  1.109852</code></pre>
<pre class="r"><code>box_m(u, t)</code></pre>
<pre><code>## # A tibble: 1 x 4
##   statistic p.value parameter method                                             
##       &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;                                              
## 1      24.0 0.00773        10 Box&#39;s M-test for Homogeneity of Covariance Matrices</code></pre>
<pre class="r"><code>man1&lt;-manova(cbind(affairs,yearsmarried,age,rating,education)~gender, data=affair)
summary(man1)</code></pre>
<pre><code>##            Df  Pillai approx F num Df den Df    Pr(&gt;F)    
## gender      1 0.20151   30.032      5    595 &lt; 2.2e-16 ***
## Residuals 599                                             
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man1)</code></pre>
<pre><code>##  Response affairs :
##              Df Sum Sq Mean Sq F value Pr(&gt;F)
## gender        1    0.9  0.8993  0.0825  0.774
## Residuals   599 6528.2 10.8985               
## 
##  Response yearsmarried :
##              Df  Sum Sq Mean Sq F value Pr(&gt;F)
## gender        1    17.1  17.078  0.5498 0.4587
## Residuals   599 18606.6  31.063               
## 
##  Response age :
##              Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## gender        1   1881 1881.48  22.591 2.512e-06 ***
## Residuals   599  49887   83.28                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response rating :
##              Df Sum Sq Mean Sq F value Pr(&gt;F)
## gender        1   0.04 0.04133  0.0339  0.854
## Residuals   599 730.16 1.21897               
## 
##  Response education :
##              Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## gender        1  547.25  547.25  112.41 &lt; 2.2e-16 ***
## Residuals   599 2916.12    4.87                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>affair %&gt;% group_by(gender) %&gt;% summarize(mean(age), mean(education))</code></pre>
<pre><code>## # A tibble: 2 x 3
##   gender `mean(age)` `mean(education)`
##   &lt;fct&gt;        &lt;dbl&gt;             &lt;dbl&gt;
## 1 female        30.8              15.3
## 2 male          34.3              17.2</code></pre>
<pre class="r"><code>pairwise.t.test(affair$age,affair$gender, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  affair$age and affair$gender 
## 
##      female 
## male 2.5e-06
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(affair$education,affair$gender, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  affair$education and affair$gender 
## 
##      female
## male &lt;2e-16
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>1 - (0.95^4)</code></pre>
<pre><code>## [1] 0.1854938</code></pre>
<pre class="r"><code>0.05/10</code></pre>
<pre><code>## [1] 0.005</code></pre>
<p>Interpretation:
A one-way MANOVA was conducted to determine the effect of gender (male or female) on five dependent variables (affairs,years married,age,rating, and education) Examination of formal test of multivariate normality assumption for each group showed normality for each group.Examination of covariance matrices for each group revealed relative homogeneity. No univariate or multivariate outliers were evident and MANOVA was considered to be an appropriate analysis technique.</p>
<p>Significant differences were found among gender for at least one of the dependent variables, Pillai trace= 0.20151, pseudoF= 30.032, p &lt;0.0001.</p>
<p>Univariate ANOVAs for each dependent variable were conducted as follow-up tests to the MANOVA, using the Bonferroni method for controlling Type I error rates for multiple comparisons. The univariate ANOVAs for age and education were also significant with p &lt; 0.0001.</p>
<p>Post hoc analysis was performed conducting pairwise comparisons to determine which gender differed in age and education. Both genders were found to differ significantly from each other in terms of age and education after adjusting for multiple comparisons(bonferroni ).</p>
<p>I performed 1 MANOVA, 5 ANOVAs, and 4 t tests, so α = 0.05/10 as significance level. The probability of at least one type I error, unadjusted, is 0.1854938. The Bonferroni corrected significance level is 0.005.</p>
<p>##Randomization:</p>
<pre class="r"><code>gen&lt;-affair %&gt;% select(gender,rating)
head(gen)</code></pre>
<pre><code>##   gender rating
## 1   male      4
## 2 female      4
## 3 female      4
## 4   male      5
## 5   male      3
## 6 female      5</code></pre>
<pre class="r"><code>ggplot(gen,aes(rating,fill=gender))+geom_histogram(bins=6.5)+facet_wrap(~gender,ncol=2)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>gen %&gt;% group_by(gender) %&gt;% summarize(means=mean(rating)) %&gt;% summarize(mean_diff=diff(means)) %&gt;% glimpse()</code></pre>
<pre><code>## Rows: 1
## Columns: 1
## $ mean_diff &lt;dbl&gt; -0.01660562</code></pre>
<pre class="r"><code>rand_dist&lt;-vector() 
for(i in 1:5000){
  new&lt;-data.frame(rating=sample(gen$rating),gen=gen$gender)
  rand_dist[i]&lt;-mean(new[new$gen==&quot;male&quot;,]$rating)
  mean(new[new$condition==&quot;female&quot;,]$rating)}

{hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;) ;  abline(v = c(-0.01660562, 0.01660562),col=&quot;red&quot;)}</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>mean(rand_dist&gt;0.01660562 | rand_dist &lt; -0.01660562)</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>mean(rand_dist&gt;-0.01660562)*2</code></pre>
<pre><code>## [1] 2</code></pre>
<pre class="r"><code>t.test(data=affair, rating~gender,)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  rating by gender
## t = 0.18491, df = 598.93, p-value = 0.8534
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.1597633  0.1929745
## sample estimates:
## mean in group female   mean in group male 
##             3.939683             3.923077</code></pre>
<p>Interpretation:
Null Hypothesis: Mean rating of marriage is the same for both genders.
Alternative Hypothesis: Mean rating of marriage is not the same for male and females.
Based on this test, we fail to reject the null hypothesis (p&gt;0.05) that the group means are all equal. There is a probability of 0.8534 to get a mean difference if the outcome data was split into every possible random grouping.</p>
<p>##Linear Regression Model:</p>
<pre class="r"><code>affair$age_r&lt;-affair$age-mean(affair$age)
affair$yearsmarried_r&lt;-affair$yearsmarried-mean(affair$yearsmarried)

fit&lt;-lm(affairs~age_r+yearsmarried_r, data= affair)
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = affairs ~ age_r + yearsmarried_r, data = affair)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.6300 -1.7312 -0.9970 -0.3918 11.6199 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     1.45591    0.13198  11.032  &lt; 2e-16 ***
## age_r          -0.04494    0.02261  -1.987   0.0473 *  
## yearsmarried_r  0.16889    0.03770   4.480 8.96e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.235 on 598 degrees of freedom
## Multiple R-squared:  0.04124,    Adjusted R-squared:  0.03804 
## F-statistic: 12.86 on 2 and 598 DF,  p-value: 3.396e-06</code></pre>
<pre class="r"><code>ggplot(affair,aes(y=age_r,x=yearsmarried_r,color=affairs))+geom_point()+stat_smooth(method=&quot;lm&quot;,se=FALSE)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>fit2&lt;-lm(affairs~age_r, data = affair)
summary(fit2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = affairs ~ age_r, data = affair)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -2.285 -1.609 -1.270 -0.949 11.051 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.45591    0.13406  10.860   &lt;2e-16 ***
## age_r        0.03382    0.01444   2.342   0.0195 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.287 on 599 degrees of freedom
## Multiple R-squared:  0.00907,    Adjusted R-squared:  0.007416 
## F-statistic: 5.483 on 1 and 599 DF,  p-value: 0.01953</code></pre>
<pre class="r"><code>ggplot(affair,aes(y=affairs,x=age_r))+geom_point()+stat_smooth(method=&quot;lm&quot;,se=FALSE)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>fit3&lt;-lm(affairs~yearsmarried_r, data = affair)
summary(fit3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = affairs ~ yearsmarried_r, data = affair)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.2106 -1.6575 -0.9937 -0.5974 11.3658 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     1.45591    0.13230  11.005   &lt;2e-16 ***
## yearsmarried_r  0.11063    0.02377   4.655    4e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.243 on 599 degrees of freedom
## Multiple R-squared:  0.03491,    Adjusted R-squared:  0.0333 
## F-statistic: 21.67 on 1 and 599 DF,  p-value: 3.996e-06</code></pre>
<pre class="r"><code>ggplot(affair,aes(y=affairs,x=yearsmarried_r))+geom_point()+stat_smooth(method=&quot;lm&quot;,se=FALSE)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>fit4&lt;-lm(affairs ~ age_r * yearsmarried_r, data=affair)
summary(fit4)</code></pre>
<pre><code>## 
## Call:
## lm(formula = affairs ~ age_r * yearsmarried_r, data = affair)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.7168 -1.7603 -1.0524 -0.4163 11.5991 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           1.646381   0.192141   8.569  &lt; 2e-16 ***
## age_r                -0.027753   0.025878  -1.072 0.283942    
## yearsmarried_r        0.152612   0.039523   3.861 0.000125 ***
## age_r:yearsmarried_r -0.004742   0.003478  -1.363 0.173359    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.233 on 597 degrees of freedom
## Multiple R-squared:  0.04422,    Adjusted R-squared:  0.03941 
## F-statistic: 9.206 on 3 and 597 DF,  p-value: 5.826e-06</code></pre>
<pre class="r"><code>#Linearity 
resids&lt;-fit$residuals
fitvals&lt;-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color=&#39;red&#39;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-4.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>fitted&lt;-lm(affairs~age_r+yearsmarried_r, data= affair)$fitted.values
ggplot()+geom_point(aes(fitted,resids))</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-5.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#Normality 
qqnorm(affair$age_r)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-6.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>shapiro.test(head(affair$age_r))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  head(affair$age_r)
## W = 0.86868, p-value = 0.221</code></pre>
<pre class="r"><code>qqnorm(affair$yearsmarried_r)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-7.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>shapiro.test(head(affair$yearsmarried_r))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  head(affair$yearsmarried_r)
## W = 0.85609, p-value = 0.1762</code></pre>
<pre class="r"><code>resids&lt;-lm(affairs~age_r+yearsmarried_r, data= affair)$residuals
ggplot()+geom_histogram(aes(resids),bins=10)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-8.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ks.test(resids, &quot;pnorm&quot;, mean=0, sd(resids))</code></pre>
<pre><code>## 
##  One-sample Kolmogorov-Smirnov test
## 
## data:  resids
## D = 0.31311, p-value &lt; 2.2e-16
## alternative hypothesis: two-sided</code></pre>
<pre class="r"><code>shapiro.test(resids)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resids
## W = 0.65307, p-value &lt; 2.2e-16</code></pre>
<pre class="r"><code>#Homoskedasticity
bptest(fit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 23.026, df = 2, p-value = 9.998e-06</code></pre>
<pre class="r"><code>ggplot(affair,aes(age_r,yearsmarried_r,color=affairs))+geom_point()</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-9.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(sandwich)
library(lmtest)
fi&lt;-lm(affairs~age_r+yearsmarried_r, data =  affair)
bptest(fit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 23.026, df = 2, p-value = 9.998e-06</code></pre>
<pre class="r"><code>coeftest(fit)</code></pre>
<pre><code>## 
## t test of coefficients:
## 
##                 Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)     1.455907   0.131975 11.0317 &lt; 2.2e-16 ***
## age_r          -0.044942   0.022613 -1.9874   0.04733 *  
## yearsmarried_r  0.168890   0.037702  4.4796 8.962e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>coeftest(fit, vcov = vcovHC(fit))</code></pre>
<pre><code>## 
## t test of coefficients:
## 
##                 Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)     1.455907   0.132322 11.0027 &lt; 2.2e-16 ***
## age_r          -0.044942   0.023802 -1.8882   0.05949 .  
## yearsmarried_r  0.168890   0.040637  4.1560 3.711e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Interpretation:</p>
<p>Predicted affairs for an average age with average years married is 1.646381. Controlling for years married, for every 1-unit increase in age, affairs goes down 0.027753 on average. Controlling for age, in persons of average years married, affairs are 0.152612 higher. Controlling for age, the slope for years married on affairs is 0.004742 less.</p>
<p>4.124% is the multiple r squared value and it is the proportion of variation in the outcome that is explained by my model. The adjusted r squared value says 3.804% of variability of affairs is explained (penalty to mitigate chance association).</p>
<p>Variance does not look pretty constant. In both formal tests of normality, we reject the null hypothesis that the true distribution is normal. Based on the Breusch-Pagan test, the p-Value &lt; 0.05 indicates that the null hypothesis can not be rejected and therefore heteroskedasticity does not exists. With the robust standard errors, the t values decreased and the p-values increased.</p>
<p>##Bootstrapped Standard errors:</p>
<pre class="r"><code>boot_sd&lt;-affair[sample(nrow(affair),replace=TRUE),]

samp_distn&lt;-replicate(1000, {
  boot_sd&lt;-affair[sample(nrow(affair),replace=TRUE),]
  fit5&lt;-lm(affairs ~ age_r * yearsmarried_r,data=boot_sd)
  coef(fit5)
  })

samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept)      age_r yearsmarried_r age_r:yearsmarried_r
## 1   0.2048709 0.02864411     0.04427715          0.003453116</code></pre>
<pre class="r"><code>summary(fit4)</code></pre>
<pre><code>## 
## Call:
## lm(formula = affairs ~ age_r * yearsmarried_r, data = affair)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.7168 -1.7603 -1.0524 -0.4163 11.5991 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           1.646381   0.192141   8.569  &lt; 2e-16 ***
## age_r                -0.027753   0.025878  -1.072 0.283942    
## yearsmarried_r        0.152612   0.039523   3.861 0.000125 ***
## age_r:yearsmarried_r -0.004742   0.003478  -1.363 0.173359    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.233 on 597 degrees of freedom
## Multiple R-squared:  0.04422,    Adjusted R-squared:  0.03941 
## F-statistic: 9.206 on 3 and 597 DF,  p-value: 5.826e-06</code></pre>
<pre class="r"><code>coeftest(fit4, vcov = vcovHC(fit4))</code></pre>
<pre><code>## 
## t test of coefficients:
## 
##                        Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)           1.6463809  0.2045691  8.0480 4.561e-15 ***
## age_r                -0.0277530  0.0285760 -0.9712 0.3318418    
## yearsmarried_r        0.1526119  0.0433119  3.5236 0.0004584 ***
## age_r:yearsmarried_r -0.0047415  0.0035804 -1.3243 0.1859133    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Interpretation:
The p-values for the corrected SEs are higher than the p-values of the uncorrected ones. Additionally the Std. Errors for the corrected SEs are also higher than the uncorrected ones.</p>
<p>##Logistic Regression Model:</p>
<pre class="r"><code>affair$y&lt;-ifelse(affair$gender==&quot;male&quot;,1,0)
fit5&lt;-glm(y~age+children+occupation, data = affair, family=binomial(link=&quot;logit&quot;))
summary(fit5)</code></pre>
<pre><code>## 
## Call:
## glm(formula = y ~ age + children + occupation, family = binomial(link = &quot;logit&quot;), 
##     data = affair)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.0841  -1.1054  -0.3685   0.9398   2.1370  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -3.90533    0.44167  -8.842   &lt;2e-16 ***
## age          0.02226    0.01146   1.942   0.0521 .  
## childrenyes  0.36836    0.22667   1.625   0.1041    
## occupation   0.64875    0.06542   9.917   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 831.76  on 600  degrees of freedom
## Residual deviance: 672.34  on 597  degrees of freedom
## AIC: 680.34
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre class="r"><code>exp(coef(fit5))</code></pre>
<pre><code>## (Intercept)         age childrenyes  occupation 
##  0.02013422  1.02251280  1.44536804  1.91314551</code></pre>
<pre class="r"><code>prob &lt;- predict(fit5, data = affair, type = &quot;response&quot;)
pred&lt;-ifelse(prob&gt;.5,1,0)
table(prediction=pred, truth = affair$y) %&gt;% addmargins()</code></pre>
<pre><code>##           truth
## prediction   0   1 Sum
##        0   213  83 296
##        1   102 203 305
##        Sum 315 286 601</code></pre>
<pre class="r"><code>#Accuracy
(213+203)/601</code></pre>
<pre><code>## [1] 0.6921797</code></pre>
<pre class="r"><code>#TPR
203/286</code></pre>
<pre><code>## [1] 0.7097902</code></pre>
<pre class="r"><code>#TNR
213/315</code></pre>
<pre><code>## [1] 0.6761905</code></pre>
<pre class="r"><code>#PPV
203/305</code></pre>
<pre><code>## [1] 0.6655738</code></pre>
<pre class="r"><code>library(plotROC)
ROCplot&lt;-ggplot(affair)+geom_roc(aes(d=y,m=prob), n.cuts=0)+  geom_segment(aes(x=0,xend=1,y=0,yend=1),lty=2) 
ROCplot</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.7783716</code></pre>
<pre class="r"><code>class_diag&lt;-function(probs,truth){
  
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]

  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  
  
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,auc)
}


k=10
data&lt;-affair[sample(nrow(affair)),]
folds&lt;-cut(seq(1:nrow(affair)),breaks=k,labels=F)

diags&lt;-NULL 
for(i in 1:k){
  train&lt;-data[folds!=i,]   
  test&lt;-data[folds==i,]
  truth&lt;-test$y
  fit6&lt;-glm(y~age+children+occupation, data = affair, family = &quot;binomial&quot;) 
  probs&lt;-predict(fit6,newdata = test,type=&quot;response&quot;)
  diags&lt;-rbind(diags,class_diag(probs,truth)) 
}

summarize_all(diags,mean)</code></pre>
<pre><code>##         acc      sens      spec       ppv       auc
## 1 0.6922678 0.7083585 0.6789069 0.6646047 0.7797899</code></pre>
<pre class="r"><code>affair$logit&lt;-predict(fit5,type=&quot;link&quot;)
affair%&gt;%ggplot()+geom_density(aes(logit,color=gender,fill=gender), alpha=.4)+
  theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+xlab(&quot;logit (log-odds)&quot;)+
  geom_rug(aes(logit,color=gender))</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-2.png" width="768" style="display: block; margin: auto;" />
Interpretation:
Controlling for children and occupation, going up 1 age multiplies odds by a factor of 1.023. Controlling for age and occupation, going up 1 children multiplies odds by a factor of 1.445.Controlling for age and children, going up 1 occupation multiplies odds by a factor of 1.913.</p>
<p>Overall Accuracy (0.692) is just proportion of correctly classified cases.Sensitivity is the true positive rate (0.710) and it is the probability of correctly detecting a male based on age, children, and occupation.Specificity is the true negative rate (0.676) and it is the probability of correctly detecting a female based on age, children, and occupation. Precision ( 0.666) is the proportion classified as male actually being a male. The auc quantifies how well we are predicting overall and it is 0.614, which is poor since the rule of thumb for AUC is 0.6-0.7 is poor. It is hard to predict gender from just age, children, and occupation.</p>
<p>The ROC curve lets us visualize trade-off between sensitivity and specificity. After the fold classification diagnostics, the acc is 0.692, the sens is 0.710, the spec is 0.676, and the ppv is 0.665. The AUC actually increased a bit to 0.772 making it fair.</p>
<p>##Logistic Regression from all variables:</p>
<pre class="r"><code>fit9&lt;-glm(y~age+religiousness+occupation+rating, data = affair, family = binomial) 
prob&lt;-predict(fit9,type=&quot;response&quot;)
class_diag(prob,affair$y)</code></pre>
<pre><code>##         acc      sens      spec       ppv       auc
## 1 0.6838602 0.7447552 0.6285714 0.6454545 0.7763792</code></pre>
<pre class="r"><code>k=10
data&lt;-affair[sample(nrow(affair)),] 
folds&lt;-cut(seq(1:nrow(affair)),breaks=k,labels=F)
diags&lt;-NULL 
for(i in 1:k){
  train&lt;-data[folds!=i,]   
  test&lt;-data[folds==i,]
  truth&lt;-test$y
  fit&lt;-glm(y~age+religiousness+occupation+rating,data=train,family=&quot;binomial&quot;)
  probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
  diags&lt;-rbind(diags,class_diag(probs,truth)) 
}
summarize_all(diags,mean)</code></pre>
<pre><code>##         acc      sens     spec       ppv       auc
## 1 0.6756557 0.7608996 0.608482 0.6423305 0.7759758</code></pre>
<pre class="r"><code>x&lt;-model.matrix(fit9)
y&lt;-as.matrix(affair$y)
cv&lt;-cv.glmnet(x,y,family = &#39;binomial&#39;)
lasso1&lt;-glmnet(x,y,family = &#39;binomial&#39;,lambda=cv$lambda.1se)
coef(lasso1)</code></pre>
<pre><code>## 6 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                        s0
## (Intercept)   -2.34193547
## (Intercept)    .         
## age            0.00774235
## religiousness  .         
## occupation     0.46353149
## rating         .</code></pre>
<pre class="r"><code>k=10
data&lt;-affair[sample(nrow(affair)),] 
folds&lt;-cut(seq(1:nrow(affair)),breaks=k,labels=F)
diags&lt;-NULL 
for(i in 1:k){
  train&lt;-data[folds!=i,]   
  test&lt;-data[folds==i,]
  truth&lt;-test$y
  fit&lt;-glm(y~age+occupation,data=train,family=&quot;binomial&quot;)
  probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
  diags&lt;-rbind(diags,class_diag(probs,truth)) 
}
summarize_all(diags,mean)</code></pre>
<pre><code>##         acc      sens      spec       ppv      auc
## 1 0.6822404 0.7527101 0.6187136 0.6429579 0.783386</code></pre>
<p>Interpretation:
Overall Accuracy (0.684) is just proportion of correctly classified cases.Sensitivity is the true positive rate (0.745) and it is the probability of correctly detecting a male based on age, religiousness, occupation and rating.Specificity is the true negative rate (0.629) and it is the probability of correctly detecting a female based on age, religiousness, occupation and rating. Precision ( 0.645) is the proportion classified as male actually being a male. The auc quantifies how well we are predicting overall and it is 0.776, which is fair since the rule of thumb for AUC is 0.7-0.8 is fair It is somewhat hard to predict gender from just age, religiousness, occupation and rating.</p>
<p>After the fold classification diagnostics, the acc is 0.674, the sens is 0.755, the spec is 0.602, the ppv is 0.636 and the auc is 0.768. All of the diagnostics actually decreased when compared with the in-sample metrics. The model is not the best at predicting gender on new data. The drop in AUC from the original indicates slight overfitting!</p>
<p>The variables that were retained were age and occupation because they were the only variables that had a non zero value. These variables are most predictive of gender!</p>
<p>After the fold classification diagnostics on the lasso selected varibales, the acc is 0.671, the sens is 0.751, the spec is 0.600, the ppv is 0.637 and the auc is 0.776. Only the ppv and the auc increased when compared to the logistic regressions above whereas the other diagnostics decreased. Same story: the model is not the best at predicting gender on new data. The model makes better predictions on the new dataset (better CV AUC!).</p>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
